spring:
  application:
    name: houme

  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: http://localhost:8080/oauth/kakao/callback
            authorization-grant-type: authorization_code
            scope: profile_nickname,account_email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    header: Authorization
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 2592000

  web:
    resources:
      add-mappings: false

openai:
  api-key: ${OPEN_AI_KEY}
  image:
    model: gpt-image-1
    n: 1
    size: 1024x1024
    quality: medium
    background: auto
    output-format: webp

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  allowed-malls: ${NAVER_ALLOWED_MALLS}  # 쉼표 구분 (예: 롯데ON,쿠팡,11번가)

cloud:
  aws:
    s3:
      bucket: houme-bucket
      bucket-domain: ${BUCKET_DOMAIN}
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  env: local

sentry:
  dsn:
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
  environment: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env

  metrics:
    tags:
      application: houme

app:
  cookie:
    domain: ""
    same-site: Lax
    secure: false

external:
  image-api:
    base-url: ${IMAGE_BASE_URL}

resilience4j:
  circuitbreaker:
    instances:
      imageClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000


logging:
  level:
    or.sopt.houme.global.aop: INFO
