-- Gemini 이미지 생성 관측 테이블의 운영 반영용 migration.
-- 적용 전 대상 DB 백업을 생성하고, 애플리케이션 배포 전에 한 번 실행한다.
-- ddl-auto:update만으로 기존 행에 NOT NULL 컬럼을 추가하면 시작이 실패할 수 있으므로,
-- 측정 이력이 없는 성능 컬럼은 NULL을 보존한다. 0으로 대체하지 않는다.

BEGIN;

CREATE TABLE IF NOT EXISTS gemini_image_generation_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    api_type VARCHAR(30) NOT NULL,
    api_path VARCHAR(255) NOT NULL,
    user_id BIGINT,
    trace_id VARCHAR(64),
    model VARCHAR(100) NOT NULL,
    prompt_chars INTEGER NOT NULL,
    reference_image_count INTEGER NOT NULL,
    requested_reference_image_count INTEGER,
    skipped_reference_image_count INTEGER,
    variant_reused_count INTEGER,
    runtime_compressed_count INTEGER,
    reference_source_bytes BIGINT,
    reference_optimized_bytes BIGINT,
    reference_base64_bytes BIGINT,
    reference_download_millis BIGINT,
    reference_optimization_millis BIGINT,
    gemini_call_millis BIGINT,
    result_bytes BIGINT,
    result_mime_type VARCHAR(100),
    result_decode_millis BIGINT,
    s3_upload_millis BIGINT,
    total_millis BIGINT,
    finish_reason VARCHAR(100),
    prompt_tokens BIGINT,
    candidate_tokens BIGINT,
    total_tokens BIGINT,
    thoughts_tokens BIGINT,
    cached_content_tokens BIGINT,
    result_url TEXT
);

-- 이미 부분적으로 생성된 테이블을 사용하는 환경도 멱등하게 보완한다.
ALTER TABLE gemini_image_generation_observations
    ADD COLUMN IF NOT EXISTS requested_reference_image_count INTEGER,
    ADD COLUMN IF NOT EXISTS skipped_reference_image_count INTEGER,
    ADD COLUMN IF NOT EXISTS variant_reused_count INTEGER,
    ADD COLUMN IF NOT EXISTS runtime_compressed_count INTEGER,
    ADD COLUMN IF NOT EXISTS reference_source_bytes BIGINT,
    ADD COLUMN IF NOT EXISTS reference_optimized_bytes BIGINT,
    ADD COLUMN IF NOT EXISTS reference_base64_bytes BIGINT,
    ADD COLUMN IF NOT EXISTS reference_download_millis BIGINT,
    ADD COLUMN IF NOT EXISTS reference_optimization_millis BIGINT,
    ADD COLUMN IF NOT EXISTS gemini_call_millis BIGINT,
    ADD COLUMN IF NOT EXISTS result_bytes BIGINT,
    ADD COLUMN IF NOT EXISTS result_mime_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS result_decode_millis BIGINT,
    ADD COLUMN IF NOT EXISTS s3_upload_millis BIGINT,
    ADD COLUMN IF NOT EXISTS total_millis BIGINT,
    ADD COLUMN IF NOT EXISTS finish_reason VARCHAR(100),
    ADD COLUMN IF NOT EXISTS prompt_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS candidate_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS total_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS thoughts_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS cached_content_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS result_url TEXT;

-- 과거 행에 실제 측정값이 없으므로 성능 컬럼의 일괄 backfill 및 NOT NULL 전환은 하지 않는다.
-- 이후 모든 행의 측정값이 확인된 컬럼만 별도 migration에서 NOT NULL 전환한다.

CREATE INDEX IF NOT EXISTS idx_gemini_image_observation_created_at
    ON gemini_image_generation_observations (created_at);

CREATE INDEX IF NOT EXISTS idx_gemini_image_observation_api_type_created_at
    ON gemini_image_generation_observations (api_type, created_at);

COMMIT;
