name: develop-cd.yml
on:
  push:
    branches: [feat/#32/develop-cd]

  pull_request:
    types: [synchronize, closed, opened]
    branches: [feat/#32/develop-cd]
    paths:
      - 'src/**'

jobs:
  set-environment:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: 환경 변수 세팅 # 배포 환경 (개발 환경인지 운영 환경인지, 지금은 불필요)
        id: set-env
        run: |
          echo ${{ github.base_ref }}
#          echo "environment=develop" >> $GITHUB_OUTPUT
#
#          if [[ ${{ github.base_ref }} == "main" ]]; then
#            echo "environment=prod" >> $GITHUB_OUTPUT
#          fi
      - name: check env
        run: echo ${{ steps.set-env.outputs.environment }}

  image-build:
    runs-on: ubuntu-latest
    needs: [set-environment]
    permissions:
      id-token: write
      contents: read
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: AWS 설정
        id: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Add application-dev.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application-dev.yml
      - name: Jib Push with RunID
        run: ./gradlew jib -Djib.to.image=528350874585.dkr.ecr.ap-northeast-2.amazonaws.com/houme \
          -Djib.to.tags=${{ github.run_id }}

  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [ set-environment, image-build ]
    permissions:
      id-token: write
      contents: read
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
      - name: Set target IP
        run: |
          STATUS=$(curl -k -o /dev/null -w "%{http_code}" "https://${{ secrets.HOUME_DOMAIN }}/actuator/health")
          echo $STATUS
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s -k https://${{ secrets.HOUME_DOMAIN }}/api/v1/env | jq -r '.env')
          else
            CURRENT_UPSTREAM=green
          fi
          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          else
            echo "error"
            exit 1
          fi

      - name: Docker 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOUME_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/houme:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

      - name: 새로운 서버 통신 확인
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.HOUME_SERVER_IP }}:${{env.STOPPED_PORT}}/actuator/healths
          max-attempts: 3
          retry-delay: 10s
          insecure: true

      - name: nginx upstream 변경
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOUME_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" | sudo tee /etc/nginx/sites-enabled/service-env.inc
            sudo nginx -t && sudo nginx -s reload

      - name: 기존 서버 중지
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOUME_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            if [ "$(sudo docker ps -aq -f name=${{ env.CURRENT_UPSTREAM }})" ]; then
              sudo docker stop ${{ env.CURRENT_UPSTREAM }}
              sudo docker rm ${{ env.CURRENT_UPSTREAM }}
            else
              echo "No container named ${{ env.CURRENT_UPSTREAM }} found. Skipping stop & remove."
            fi

      - name: 기존 도커 이미지 제거
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOUME_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker image prune -f
  notify-discord-cd:
    needs: deploy # deploy job이 끝나야 실행
    runs-on: ubuntu-latest
    if: always()  # 성공하든 실패하든
    steps:
      - name: 디스코드 알림
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          STATUS: ${{ needs.deploy.result }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          message="✅ CD 성공"
          color=3066993 # 초록
          if [ "$STATUS" != "success" ]; then
            message="❌ CD 실패"
            color=15158332 # 빨강
          fi
          # 디스코드에 보낼 payload JSON 생성
          # actor: 작성자, message: CD 완수 메시지, pr_url: PR 링크
          pr_title="$PR_TITLE"
          payload=$(jq -n --arg actor "${{ github.actor }}" \
                          --arg message "$message" \
                          --arg pr_url "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" \
                          --arg pr_title "$pr_title" \
                          --argjson color "$color" \
            '{
              # discord에 등록될 메시지 형태
              "embeds": [
                {
                  "title": "🙈새로운 배포 결과!",
                  "description": "\($actor)님이 배포를 진행했습니다!\n📄 \($pr_title) \n \($message)\n🔗[워크플로우 실행 확인하기](\($pr_url))",
                  "color": $color,
                  "timestamp": now | todateiso8601
                }
              ]
            }')

            # discord  웹훅 URL로 서버에 Post 요청
          curl  -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                "$DISCORD_WEBHOOK"
  create-pr:
     # if: needs.set-environment.outputs.environment == 'develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 레포지토리 내용 수정 권한
      pull-requests: write # PR 생성 권한
    needs: [ set-environment, deploy ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gh auth login
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | gh auth login --with-token
      - name: create branch
        run: |
          git checkout -b release/${{ github.run_id }}
          git push origin release/${{ github.run_id }}
      - name: create pr
        run: |
          gh pr create --base master --head release/${{ github.run_id }} --title "[DEPLOY] release/${{ github.run_id }} -> master" --body "release pr"